### ISSUE TITLE
Error while installing packages (more specifically, package aiohtttp)

### ISSUE THREAD

**Issue by 000yesnt** [Senvr/SenvrMachine#2]
everything goes well and shti until this

```
   Running setup.py (path:/tmp/pip-build-x0iIQO/aiohttp/setup.py) egg_info for package aiohttp
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-x0iIQO/aiohttp/setup.py", line 60, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.2+")
    RuntimeError: aiohttp requires Python 3.4.2+
Cleaning up...
  Removing source in /tmp/pip-RbtbBy-build
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-x0iIQO/aiohttp/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 725, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-x0iIQO/aiohttp/

```

why in fuck is this happening
i have python 3.6.8

**Comment by Senvr** [comment]
Try:
`pip install --upgrade setuptools`
If that dont work:
`sudo apt install python3.6-dev lybmysqlclient-dev`

**Comment by 000yesnt** [comment]
I installed aiohttp separately and found out the issue: pip was using Python 2.7 instead of 3.x! Now the installation runs smoothly.
